### PR TITLE
Fix browser stderr/stdout in signin, fixing #177

### LINKED ISSUE #177: fix output from browser in `taskcluster signin`
After running `stdout` looks like:
```
Created new window in existing browser session.
export TASKCLUSTER_CLIENT_ID='mozilla-ldap/jojensen@mozilla.com/cli'
export TASKCLUSTER_ACCESS_TOKEN=
```
and useful messages to `stderr`... 

Probably we need to hack the library we use to open the browser to redirect it's output to stderr...

### PR DESCRIPTION
**Pull request by jonasfj**
This should fix #177

### CODE REVIEW

File: cmds/signin/signin.go [hunk 1]
```diff
@@ -87,11 +88,11 @@ func cmdSignin(cmd *cobra.Command, _ []string) error {
...
 		if csh {
-			fmt.Fprintln(cmd.OutOrStdout(), "setenv TASKCLUSTER_CLIENT_ID '" + qs.Get("clientId") + "'")
-			fmt.Fprintln(cmd.OutOrStdout(), "setenv TASKCLUSTER_ACCESS_TOKEN '" + qs.Get("accessToken") + "'")
+			fmt.Fprintln(cmd.OutOrStdout(), "setenv TASKCLUSTER_CLIENT_ID '"+qs.Get("clientId")+"'")
+			fmt.Fprintln(cmd.OutOrStdout(), "setenv TASKCLUSTER_ACCESS_TOKEN '"+qs.Get("accessToken")+"'")
 		} else {
-			fmt.Fprintln(cmd.OutOrStdout(), "export TASKCLUSTER_CLIENT_ID='" + qs.Get("clientId") + "'")
-			fmt.Fprintln(cmd.OutOrStdout(), "export TASKCLUSTER_ACCESS_TOKEN='" + qs.Get("accessToken") + "'")
+			fmt.Fprintln(cmd.OutOrStdout(), "export TASKCLUSTER_CLIENT_ID='"+qs.Get("clientId")+"'")
+			fmt.Fprintln(cmd.OutOrStdout(), "export TASKCLUSTER_ACCESS_TOKEN='"+qs.Get("accessToken")+"'")
```
Comment (jonasfj) [inline cmds/signin/signin.go]: I guess my lint-on-save did some tricks here...

Comment (djmitche) [reply cmds/signin/signin.go]: yeah, gofmt is great until different versions of it fight with themselves.. can you revert this bit?

Comment (jonasfj) [reply cmds/signin/signin.go]: I'd rather not... this is the gofmt version that tc-worker uses... and then one we should be using everywhere... I think it's just that this repo doesn't run sufficient linter tests...
